config/routes.rb
Rails.application.routes.draw do
  root 'participants#index'

  resources :shuttle_forms, only: %i[index edit update]
  post 'shuttle_forms/menu/:id', to: 'shuttle_forms#turbo_menu', as: :shuttle_form_menu

  mount ActionCable.server => '/cable'
  resources :folders
  resources :meetings
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords' }
  resources :links, except: %i[show]

  resources :pads
  post 'pads/:id/toggle_archive', to: 'pads#toggle_archive', as: 'pad_toggle_archive'
  post 'pads/:id/toggle_bookmark', to: 'pads#toggle_bookmark', as: 'pad_toggle_bookmark'

  resources :visios
  post 'visios/:id/toggle_archive', to: 'visios#toggle_archive', as: 'visio_toggle_archive'
  post 'visios/:id/toggle_bookmark', to: 'visios#toggle_bookmark', as: 'visio_toggle_bookmark'
  get 'visios/:id/visio_url', to: 'visios#url', as: 'visio_url'
  get '/visios/:id/button_to_bbb', to: 'visios#button_to_bbb', as: 'button_to_bbb'
  get '/visios/:id/recordings', to: 'visio_recordings#index', as: 'visio_recordings'
  delete 'visios/:id/recordings/:record_id' => 'visio_recordings#destroy', as: 'visio_recordings_destroy'
  get '/visios/:id/recordings_list', to: 'visio_recordings#visio_recordings', as: 'visio_recordings_list'
  get 'visios/:id/recordings/after_destroy', to: 'visio_recordings#after_destroy', as: 'visio_recordings_after_destroy'
  get 'visios/:id/recordings/:record_id/download', to: 'visio_recordings#download', as: 'visio_recording_download'

  resources :memos
  post 'memos/:id/toggle_archive', to: 'memos#toggle_archive', as: 'memo_toggle_archive'
  post 'memos/:id/toggle_bookmark', to: 'memos#toggle_bookmark', as: 'memo_toggle_bookmark'

  resources :users, only: %i[edit update]

  resources :config_modules do
    resources :instances
  end

  resources :services, only: %i[index show]

  # Choix de la promo
  get 'participants', to: 'participants#index', as: 'participants'
  post 'participants/:id', to: 'participants#choose', as: 'participant'

  resources :classrooms
  get 'classrooms/:id/groups', to: 'groups#index', as: 'groups'
  post 'classrooms/:id/groups', to: 'groups#create'
  get 'classrooms/:id/groups/:group_id', to: 'groups#show', as: 'group'
  delete 'classrooms/:id/groups/:group_id', to: 'groups#destroy'
  patch 'classrooms/:id/groups/:group_id', to: 'groups#update', as: 'group_update'
  post 'classrooms/:id/participant/:participant_id/enable_module/:module_id', to: 'classrooms#enable_module_for_participant',
                                                                              as: 'enable_module_for_participant'
  post 'classrooms/:id/participant/:participant_id/disable_module/:module_id', to: 'classrooms#disable_module_for_participant',
                                                                               as: 'disable_module_for_participant'

  post 'login' => 'users#login'
  get 'logout' => 'users#logout', as: :logout

  get 'about' => 'about#index', as: 'about'

  get 'config_modules/:domain_id/infos' => 'config_modules#infos'

  get 'invitations/from/:invitable_type/:invitable_id', to: 'invitations#index', as: :invitations
  get 'invitations/from/:invitable_type/:invitable_id/groups', to: 'invitations#invite_per_groups',
                                                               as: :invite_per_groups
  post 'invitations/from/:invitable_type/:invitable_id/group/:id', to: 'invitations#invite_group_add',
                                                                   as: :invite_group_add
  delete 'invitations/from/:invitable_type/:invitable_id/group/:id', to: 'invitations#invite_group_del',
                                                                     as: :invite_group_del
  post 'invitations/from/:invitable_type/:invitable_id/participant/:id', to: 'invitations#invite_participant_add',
                                                                         as: :invite_participant_add
  delete 'invitations/from/:invitable_type/:invitable_id/participant/:id', to: 'invitations#invite_participant_del',
                                                                           as: :invite_participant_del
  get 'invitations/from/:invitable_type/:invitable_id/participants', to: 'invitations#invite_per_participants',
                                                                     as: :invite_per_participants
  post 'invitations/from/:invitable_type/:invitable_id/emails', to: 'invitations#invite_per_emails',
                                                                as: :invite_per_emails
  patch 'invitations/from/:invitable_type/:invitable_id/emails', to: 'invitations#invite_per_emails_submit',
                                                                 as: :invite_per_emails_submit
  post 'invitations/from/:invitable_type/:invitable_id/groups/:id', to: 'invitations#invite_add_group',
                                                                    as: :invite_one_group
  patch 'invitations/:id', to: 'invitations#resend', as: :resend_invitation
  delete 'invitations/:id', to: 'invitations#destroy', as: :destroy_invitation

  get 'folders/:id/files/:file_id', to: 'folders#file', as: 'file'
  patch 'folders/:id/files/:file_id', to: 'folders#rename_file', as: 'rename_file'
  delete 'folders/:id/files/:file_id', to: 'folders#delete_file', as: 'delete_file'
  patch 'folders/:id/files/:file_id/move_or_copy', to: 'folders#move_or_copy_file', as: 'move_or_copy_file'
  get 'folders/:id/bookmark', to: 'folders#bookmark', as: 'bookmark_folder'
  get 'folders/:id/file/:file_id/bookmark', to: 'folders#bookmark_file', as: 'bookmark_file'
  delete 'folders/:id/elements', to: 'folders#delete_elements', as: 'folder_delete_elements'
  post 'folders/:id/files', to: 'folders#create_blank_file'
  patch 'folders/:id/move_or_copy', to: 'folders#move_or_copy_folder', as: 'move_or_copy_folder'
  get 'folders/:id/details', to: 'folders#details', as: 'details_folder'
  get 'folders/:id/files/:file_id/details', to: 'folders#file_details', as: 'details_file'
  get 'folders_search', to: 'folders#search'
  get 'folders_tree', to: 'folders#tree', as: :tree_folder
  get 'folders/:id/zip', to: 'folders#zip', as: :folder_zip

  get 'wopi/files/:id/contents', to: 'wopi#filecontent', as: 'wopi_filecontent'
  post 'wopi/files/:id/contents', to: 'wopi#update_filecontent'
  get 'wopi/files/:id', to: 'wopi#file', as: 'wopi_file'

  get 'end_visio', to: 'external_pages#end_visio', as: 'end_visio'
end

app/controllers/shuttle_forms_controller.rb
class ShuttleFormsController < BichikController
  before_action :set_shuttle_form, only: %i[edit update]
  before_action :set_teaching_units, only: %i[index edit turbo_menu]
  before_action :set_menu_message, only: %i[index edit turbo_menu]

  def index; end

  def turbo_menu
    active_tu = TeachingUnit.find(params[:id])

    render turbo_stream: turbo_stream.replace('shuttle_form_menu_teacher', partial: 'menu_teacher',
                                                                           locals: { teaching_units: @teaching_units,
                                                                                     active_tu:,
                                                                                     message: @menu_message })
  end

  def edit; end

  def update
    params_to_update = shuttle_form_params.merge(signatures)
    if @shuttle_form.update(params_to_update)
      flash[:notice] = 'La fiche navette a été mise à jour.'
      render turbo_stream: [
        turbo_stream.replace('shuttle_form', partial: 'form', locals: { shuttle_form: @shuttle_form }),
        flash_stream
      ]
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_teaching_units
    @teaching_units = current_classroom.teaching_units.where('start_date<?', Date.today).order('start_date DESC')
  end

  def set_menu_message
    @menu_message = ''

    if current_classroom.learnings.count.zero?
      @menu_message = 'Aucun stagiaire dans cette promo'
    elsif @teaching_units.count.zero?
      first_teaching_unit = current_classroom.teaching_units.order(:start_date).first
      @menu_message = if first_teaching_unit
                        'La première fiche navette sera disponible à partir ' \
                          "du #{first_teaching_unit.start_date.strftime('%d/%m/%Y')}"
                      else
                        'Aucune unité pédagogique pour cette promo'
                      end
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_shuttle_form
    @shuttle_form = ShuttleForm.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def shuttle_form_params
    permitted = []
    permissions = current_participant.shuttle_form_permissions(@shuttle_form)
    if permissions[:learner_theory][:w]
      permitted += %i[learner_theory1 learner_theory2 learner_theory3 learner_theory4
                      learner_theory5]
    end
    if permissions[:learner_training][:w]
      permitted += %i[learner_training1 learner_training2 learner_training3
                      learner_training4 learner_training5 learner_training6]
    end
    if permissions[:tutor_training][:w]
      permitted += %i[tutor_training1 tutor_training2 tutor_training3 tutor_training4
                      tutor_training5 tutor_training6]
    end
    permitted << 'teacher_theory1' if permissions[:teacher_theory][:w]
    permitted << 'teacher_training1' if permissions[:teacher_training][:w]
    params.require(:shuttle_form).permit(permitted)
  end

  def signatures
    sign_params = {}
    if params['learner_theory_signature']
      sign_params[:learner_theory_signed_at] = DateTime.now
      sign_params[:learner_theory_signed] = true
      sign_params[:learner_status] = :learner_theory_signed
    end
    if params['teacher_theory_signature']
      sign_params[:teacher_theory_signed_at] = DateTime.now
      sign_params[:teacher_theory_signed_by_id] = current_user.id
      sign_params[:teacher_status] = :teacher_theory_signed
    end
    if params['learner_training_signature']
      sign_params[:learner_training_signed_at] = DateTime.now
      sign_params[:learner_training_signed] = true
      sign_params[:learner_status] = :learner_training_signed
    end
    if params['teacher_training_signature']
      sign_params[:teacher_training_signed_at] = DateTime.now
      sign_params[:teacher_training_signed_by_id] = current_user.id
      sign_params[:teacher_status] = :teacher_training_signed
    end
    if params['tutor_training_signature']
      sign_params[:tutor_training_signed_at] = DateTime.now
      sign_params[:tutor_training_signed_by_id] = current_user.id
      sign_params[:tutor_status] = :tutor_signed
    end

    sign_params
  end
end

app/views/shuttle_forms/_form.html.erb
<%= turbo_stream_from shuttle_form %>

<%= turbo_frame_tag 'shuttle_form', class: 'flex w-full' do %>
  <div class='m-0 md:m-5 w-full'>
    <% if shuttle_form.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(shuttle_form.errors.count, "error") %> prohibited this shuttle_form from being saved:</h2>

        <ul>
          <% shuttle_form.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <% permissions = current_participant.shuttle_form_permissions(shuttle_form) %>
    <div class='p-4 bg-gray-200 dark:bg-gray-900 rounded-lg'>
      <%= render 'form_learner_theory', shuttle_form:, permissions: permissions[:learner_theory] %>
      <%= render 'form_teacher_theory', shuttle_form:, permissions: permissions[:teacher_theory] %>
    </div>
    <div class='p-4 bg-gray-200 dark:bg-gray-900 rounded-lg mt-4'>
      <%= render 'form_learner_training', shuttle_form:, permissions: permissions[:learner_training] %>
      <%= render 'form_tutor_training', shuttle_form:, permissions: permissions[:tutor_training] %>
      <%= render 'form_teacher_training', shuttle_form:, permissions: permissions[:teacher_training] %>
    </div>
  </div>
<% end %>

app/views/shuttle_forms/_form_learner_theory.html.erb
<%# locals: (shuttle_form:, permissions:) -%>
<div class='flex flex-col items-center text-2xl text-center'>
  <h2>
    <div class='font-bold'><%= shuttle_form.teaching_unit.name %></div>
    <div><%= "du #{l(shuttle_form.teaching_unit.start_date, format: :xs)} au #{l(shuttle_form.teaching_unit.end_date, format: :xs)}" %></div>
  </h2>
</div>
<h3 class='text-xl mt-10 flex items-center gap-2'>
  <%= icon('fa-solid', 'chalkboard-teacher', class: 'fa-2x') %>
  <span>Fiche suivi stagiaire</span>
</h3>
<% if permissions[:r] %>
  <% write = permissions[:w] %>
  <%= form_with(model: shuttle_form, class: "contents") do |form| %>
    <div class="my-5">
      <%= form.label "Ce que je retiens de la période de formation" %>
      <%= form.text_area :learner_theory1, rows: 4, class: "block shadow rounded-md #{write ? 'border-2 border-bichik-100' : 'bg-gray-400'} outline-none px-3 py-2 mt-2 w-full text-gray-800", readonly: !write %>
    </div>
    <div class="my-5">
      <%= form.label "Ce que j’ai envie de mettre au travail sur le terrain" %>
      <%= form.text_area :learner_theory2, rows: 4, class: "block shadow rounded-md #{write ? 'border-2 border-bichik-100' : 'bg-gray-400'} outline-none px-3 py-2 mt-2 w-full text-gray-800", readonly: !write %>
    </div>
    <div class="my-5">
      <%= form.label "Les objectifs fixés pour la période en structure qui vient" %>
      <%= form.text_area :learner_theory3, rows: 4, class: "block shadow rounded-md #{write ? 'border-2 border-bichik-100' : 'bg-gray-400'} outline-none px-3 py-2 mt-2 w-full text-gray-800", readonly: !write %>
    </div>
    <% if write %>
      <div class="flex gap-2 items-center">
        <%= form.submit 'Enregistrer', class: "rounded-lg py-3 px-5 bg-bichik-200 hover:bg-bichik-210 text-white inline-block font-medium cursor-pointer" %>
        <%= form.submit 'Signer', name: 'learner_theory_signature', class: "rounded-lg py-3 px-5 bg-bichik-100 hover:bg-bichik-110 text-white inline-block font-medium cursor-pointer", data: { turbo_confirm: "Etes-vous sûr de vouloir signer cette section ? Aucune modification ne sera possible après cette action." } %>
        <span class='text-xs'><%= "(sera automatiquement signé le #{l(@shuttle_form.teaching_unit.end_date + 2.day)})" %></span>
      </div>
    <% elsif shuttle_form.learner_theory_signed_at %>
      <span class='ml-10 gap-2 items-center bg-gray-400 dark:bg-gray-200 rounded-lg p-1 text-white dark:text-gray-800 text-sm'>
        <% if shuttle_form.learner_theory_signed %>
          <%= icon('fa-solid', 'file-signature') %>
          <%= "a été signé le #{l(shuttle_form.learner_theory_signed_at.in_time_zone(current_timezone))} par #{shuttle_form.learning.user.name}" %>
        <% else %>
          <%= icon('fa-solid', 'calendar-check') %>
          <%= "a été fermé automatiquement le #{l(shuttle_form.learner_theory_signed_at.in_time_zone(current_timezone))}" %>
        <% end %>
      </span>
    <% end %>
  <% end %>
<% else %>
  <span class='ml-10 gap-2 items-center bg-gray-400 dark:bg-gray-200 rounded-lg p-1 text-white dark:text-gray-800 text-sm'>
    <i class="fa-regular fa-hourglass-half"></i>
    Accessible au plus tard le <%= l(@shuttle_form.teaching_unit.end_date + 2.day) %>
  </span>
<% end %>

app/views/shuttle_forms/_form_learner_training.html.erb
<%# locals: (shuttle_form:, permissions:) -%>

<div class='flex flex-col items-center text-2xl text-center mt-4'>
  <h2>
    <div class='font-bold'>Terrain professionnel</div>
  </h2>
</div>

<h3 class='text-xl mt-10 flex items-center gap-2'>
  <%= icon('fa-solid', 'chalkboard-teacher', class: 'fa-2x') %>
  <span>Fiche suivi stagiaire</span>
</h3>

<% if permissions[:r] %>
  <% write = permissions[:w] %>
  <%= form_with(model: shuttle_form, class: "contents") do |form| %>

    <div class="my-5">
      <%= form.label "Les missions et tâches que j’ai effectuées" %>
      <%= form.text_area :learner_training1, rows: 4, class: "block shadow rounded-md #{write ? 'border-2 border-bichik-100' : 'bg-gray-400'} outline-none px-3 py-2 mt-2 w-full text-gray-800", readonly: !write %>
    </div>

    <div class="my-5">
      <%= form.label "Les difficultés que j’ai rencontrées" %>
      <%= form.text_area :learner_training2, rows: 4, class: "block shadow rounded-md #{write ? 'border-2 border-bichik-100' : 'bg-gray-400'} outline-none px-3 py-2 mt-2 w-full text-gray-800", readonly: !write %>
    </div>

    <div class="my-5">
      <%= form.label "Les objectifs fixés que j’ai atteints" %>
      <%= form.text_area :learner_training3, rows: 4, class: "block shadow rounded-md #{write ? 'border-2 border-bichik-100' : 'bg-gray-400'} outline-none px-3 py-2 mt-2 w-full text-gray-800", readonly: !write %>
    </div>

    <% if write %>
      <div class="flex gap-2">
        <%= form.submit 'Enregistrer', class: "rounded-lg py-3 px-5 bg-bichik-200 hover:bg-bichik-210 text-white inline-block font-medium cursor-pointer" %>
        <%= form.submit 'Signer', name: 'learner_training_signature', class: "rounded-lg py-3 px-5 bg-bichik-100 hover:bg-bichik-110 text-white inline-block font-medium cursor-pointer", data: { turbo_confirm: "Etes-vous sûr de vouloir signer cette section ? Aucune modification ne sera possible après cette action." } %>
        <%= "sera automatiquement signé le #{l(@shuttle_form.teaching_unit.training_end_date)}" %>
      </div>
    <% elsif shuttle_form.learner_training_signed_at %>
      <span class='ml-10 gap-2 items-center bg-gray-400 dark:bg-gray-200 rounded-lg p-1 text-white dark:text-gray-800 text-sm'>
        <% if shuttle_form.learner_training_signed %>
          <%= icon('fa-solid', 'file-signature') %>
          <%= "a été signé le #{l(shuttle_form.learner_training_signed_at.in_time_zone(current_timezone))} par #{shuttle_form.learning.user.name}" %>
        <% else %>
          <%= icon('fa-solid', 'calendar-check') %>
          <%= "a été fermé automatiquement le #{l(shuttle_form.learner_training_signed_at.in_time_zone(current_timezone))}" %>
        <% end %>
      </span>
    <% end %>
  <% end %>
<% else %>
  <span class='ml-10 gap-2 items-center bg-gray-400 dark:bg-gray-200 rounded-lg p-1 text-white dark:text-gray-800 text-sm'><i class="fa-regular fa-hourglass-half"></i> Accessible au plus tard le <%= l(@shuttle_form.teaching_unit.training_end_date) %></span>
<% end %>

app/views/shuttle_forms/_menu_learner.html.erb
<%# locals: (teaching_units:, active_tu: nil, message: nil) -%>

<% shuttle_forms = ShuttleForm.joins(learning: :participant).joins(:teaching_unit).where('learning.participant': current_participant).where('start_date<=?', Date.today).order('teaching_units.start_date DESC') %>

<%= turbo_frame_tag 'shuttle_form_menu_learner' do %>
  <div class='flex flex-col p-4 dark:text-gray-200 bg-gray-300 dark:bg-gray-600 x-data h-full'>
    <% if shuttle_forms.size.zero? %>
      <div class='flex gap-2 items-center text-gray-800 dark:text-gray-200 text-sm'>
        <%= icon('fa-solid', 'triangle-exclamation', class: 'fa-2x') %>
        <%= message %>
      </div>
    <% end %>
    <% shuttle_forms.each do |sf| %>
      <div>
        <%= link_to edit_shuttle_form_path(sf), class: 'flex bg-gray-100 dark:bg-gray-800 p-2 mt-2 cursor-pointer rounded-lg hover:bg-white dark:hover:bg-gray-900', 'data-turbo-frame': '_top' do %>
          <div class='flex items-center mr-2'>
            <%= icon("#{sf.teaching_unit == active_tu ? 'fa-solid' : 'fa-regular'}", 'circle') %>
          </div>
          <div class='flex flex-col'>
            <div class="<%= sf.teaching_unit==active_tu && 'font-bold'%>"><%= sf.teaching_unit.name %></div>
            <div><%= "du #{l(sf.teaching_unit.start_date, format: :xs)} au #{l(sf.teaching_unit.end_date, format: :xs)}" %></div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shuttle_forms/_menu_teacher.html.erb
<%# locals: (teaching_units:, active_tu: teaching_units.first, active_sf: nil, message: nil) -%>
<%= turbo_frame_tag 'shuttle_form_menu_teacher' do %>
  <div class='flex flex-col p-4 dark:text-gray-200 bg-gray-300 dark:bg-gray-600 x-data h-full'>
    <% unless @menu_message.empty? %>
      <div class='flex gap-2 items-center text-gray-800 dark:text-gray-200 text-sm'>
        <%= icon('fa-solid', 'triangle-exclamation', class: 'fa-2x') %>
        <%= message %>
      </div>
    <% else %>
      <% teaching_units.each do |tu| %>
        <div>
          <%= link_to shuttle_form_menu_path(tu), class: 'flex bg-gray-100 dark:bg-gray-800 p-2 mt-2 cursor-pointer rounded-tr-lg rounded-bl-lg', data: { turbo_method: :post } do %>
            <div class='flex items-center mr-2'><%= icon('fa-solid', "#{tu == active_tu ? 'chevron-down' : 'chevron-left'}") %></div>
            <div class='flex flex-col'>
              <div class="<%= tu==active_tu && 'font-bold'%>"><%= tu.name %></div>
              <div><%= "du #{l(tu.start_date, format: :xs)} au #{l(tu.end_date, format: :xs)}" %></div>
            </div>
          <% end %>
          <% if tu == active_tu %>
            <ul class="ml-6 pb-2 rounded-b-lg bg-gray-100 dark:bg-gray-800">
              <% i = 0 %>
              <% current_participant.participable.involved_shuttle_forms.where(teaching_unit: tu).each do |sf| %>
                <%= link_to edit_shuttle_form_path(sf), 'data-turbo-frame': '_top' do %>
                  <% i += 1 %>
                  <li class='text-sm <%= i.odd? ? 'bg-gray-200 dark:bg-gray-700' : 'bg-gray-100 dark:bg-gray-800' %> hover:bg-gray-400 dark:hover:bg-gray-900 pl-2<%= "font-extrabold" if @shuttle_form && @shuttle_form == sf %>'>
                    <% if active_sf == sf %>
                      <%= icon('fa-solid', 'caret-right', class: 'pl-1') %>
                    <% end %>
                    <%= sf.learning.user.name %>
                  </li>
                <% end %>
              <% end %>
            </ul>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/shuttle_forms/_shuttle_form.html.erb
<div id="<%= dom_id shuttle_form %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Teaching unit:</strong>
    <%= shuttle_form.teaching_unit.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Learning:</strong>
    <%= shuttle_form.learning.user.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Learner theory1:</strong>
    <%= shuttle_form.learner_theory1 %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Learner theory signature:</strong>
    <%= shuttle_form.learner_theory_signed_at %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this shuttle form", shuttle_form, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this shuttle form", edit_shuttle_form_path(shuttle_form), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/shuttle_forms/edit.html.erb
<%= render partial:'application/page_title', locals: {title: "#{t('modules.shuttleform.title')} - #{@shuttle_form.learning.user.name}", icon: 'route'} %>

<div class='flex'>
  <div class='hidden lg:flex'>
    <% if current_participant.learning? %>
      <%= render 'menu_learner', teaching_units: @teaching_units, active_tu: @shuttle_form.teaching_unit  %>
    <% else %>
      <%= render 'menu_teacher', teaching_units: @teaching_units, active_tu: @shuttle_form.teaching_unit, active_sf: @shuttle_form  %>
    <% end %>
  </div>
  <div class='flex w-full'>
    <%= render "form", shuttle_form: @shuttle_form %>
  </div>
</div>

app/views/shuttle_forms/index.html.erb
<%= render partial:'application/page_title', locals: {title: t('modules.shuttleform.title'), icon: 'route'} %>

<div class="flex">
  <div class='w-full lg:w-auto'>
    <% if current_participant.learning?  %>
      <%= render 'menu_learner', teaching_units: @teaching_units, message: @menu_message %>
    <% else %>
      <%= render 'menu_teacher', teaching_units: @teaching_units, message: @menu_message %>
    <% end %>
  </div>
  <%= turbo_frame_tag 'shuttle_form', class: 'flex w-full hidden lg:flex' do %>
    <div class='flex flex-col w-full items-center p-6 pt-16 gap-4 text-2xl text-gray-400'>
      <span><%= icon('fa-solid', 'route', class: 'fa-4x') %></span>
      <span class='m-4'>Sélectionnez une fiche navette dans le menu de gauche</span>
    </div>
  <% end %>
</div>

app/views/shuttle_forms/menu.html.erb
<% render 'menu', teaching_units: @teaching_units, active: @active %>

app/views/shuttle_forms/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New shuttle form</h1>

  <%= render "form", shuttle_form: @shuttle_form %>

  <%= link_to "Back to shuttle forms", shuttle_forms_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/shuttle_forms/show.html.erb
<%= render partial:'application/page_title', locals: {title: t('modules.shuttleform.title'), icon: 'route'} %>

<div class="flex flex-col m-5">

  <%= render @shuttle_form %>

  <%= link_to "Edit this shuttle_form", edit_shuttle_form_path(@shuttle_form), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this shuttle_form", shuttle_form_path(@shuttle_form), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
  </div>
  <%= link_to "Back to shuttle_forms", shuttle_forms_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>
</div>