config/routes.rb
Rails.application.routes.draw do
  root 'participants#index'

  resources :shuttle_forms, only: %i[index edit update]
  post 'shuttle_forms/menu/:id', to: 'shuttle_forms#turbo_menu', as: :shuttle_form_menu

  mount ActionCable.server => '/cable'
  resources :folders
  resources :meetings
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords' }
  resources :links, except: %i[show]

  resources :pads
  post 'pads/:id/toggle_archive', to: 'pads#toggle_archive', as: 'pad_toggle_archive'
  post 'pads/:id/toggle_bookmark', to: 'pads#toggle_bookmark', as: 'pad_toggle_bookmark'

  resources :visios
  post 'visios/:id/toggle_archive', to: 'visios#toggle_archive', as: 'visio_toggle_archive'
  post 'visios/:id/toggle_bookmark', to: 'visios#toggle_bookmark', as: 'visio_toggle_bookmark'
  get 'visios/:id/visio_url', to: 'visios#url', as: 'visio_url'
  get '/visios/:id/button_to_bbb', to: 'visios#button_to_bbb', as: 'button_to_bbb'
  get '/visios/:id/recordings', to: 'visio_recordings#index', as: 'visio_recordings'
  delete 'visios/:id/recordings/:record_id' => 'visio_recordings#destroy', as: 'visio_recordings_destroy'
  get '/visios/:id/recordings_list', to: 'visio_recordings#visio_recordings', as: 'visio_recordings_list'
  get 'visios/:id/recordings/after_destroy', to: 'visio_recordings#after_destroy', as: 'visio_recordings_after_destroy'
  get 'visios/:id/recordings/:record_id/download', to: 'visio_recordings#download', as: 'visio_recording_download'

  resources :memos
  post 'memos/:id/toggle_archive', to: 'memos#toggle_archive', as: 'memo_toggle_archive'
  post 'memos/:id/toggle_bookmark', to: 'memos#toggle_bookmark', as: 'memo_toggle_bookmark'

  resources :users, only: %i[edit update]

  resources :config_modules do
    resources :instances
  end

  resources :services, only: %i[index show]

  # Choix de la promo
  get 'participants', to: 'participants#index', as: 'participants'
  post 'participants/:id', to: 'participants#choose', as: 'participant'

  resources :classrooms
  get 'classrooms/:id/groups', to: 'groups#index', as: 'groups'
  post 'classrooms/:id/groups', to: 'groups#create'
  get 'classrooms/:id/groups/:group_id', to: 'groups#show', as: 'group'
  delete 'classrooms/:id/groups/:group_id', to: 'groups#destroy'
  patch 'classrooms/:id/groups/:group_id', to: 'groups#update', as: 'group_update'
  post 'classrooms/:id/participant/:participant_id/enable_module/:module_id', to: 'classrooms#enable_module_for_participant',
                                                                              as: 'enable_module_for_participant'
  post 'classrooms/:id/participant/:participant_id/disable_module/:module_id', to: 'classrooms#disable_module_for_participant',
                                                                               as: 'disable_module_for_participant'

  post 'login' => 'users#login'
  get 'logout' => 'users#logout', as: :logout

  get 'about' => 'about#index', as: 'about'

  get 'config_modules/:domain_id/infos' => 'config_modules#infos'

  get 'invitations/from/:invitable_type/:invitable_id', to: 'invitations#index', as: :invitations
  get 'invitations/from/:invitable_type/:invitable_id/groups', to: 'invitations#invite_per_groups',
                                                               as: :invite_per_groups
  post 'invitations/from/:invitable_type/:invitable_id/group/:id', to: 'invitations#invite_group_add',
                                                                   as: :invite_group_add
  delete 'invitations/from/:invitable_type/:invitable_id/group/:id', to: 'invitations#invite_group_del',
                                                                     as: :invite_group_del
  post 'invitations/from/:invitable_type/:invitable_id/participant/:id', to: 'invitations#invite_participant_add',
                                                                         as: :invite_participant_add
  delete 'invitations/from/:invitable_type/:invitable_id/participant/:id', to: 'invitations#invite_participant_del',
                                                                           as: :invite_participant_del
  get 'invitations/from/:invitable_type/:invitable_id/participants', to: 'invitations#invite_per_participants',
                                                                     as: :invite_per_participants
  post 'invitations/from/:invitable_type/:invitable_id/emails', to: 'invitations#invite_per_emails',
                                                                as: :invite_per_emails
  patch 'invitations/from/:invitable_type/:invitable_id/emails', to: 'invitations#invite_per_emails_submit',
                                                                 as: :invite_per_emails_submit
  post 'invitations/from/:invitable_type/:invitable_id/groups/:id', to: 'invitations#invite_add_group',
                                                                    as: :invite_one_group
  patch 'invitations/:id', to: 'invitations#resend', as: :resend_invitation
  delete 'invitations/:id', to: 'invitations#destroy', as: :destroy_invitation

  get 'folders/:id/files/:file_id', to: 'folders#file', as: 'file'
  patch 'folders/:id/files/:file_id', to: 'folders#rename_file', as: 'rename_file'
  delete 'folders/:id/files/:file_id', to: 'folders#delete_file', as: 'delete_file'
  patch 'folders/:id/files/:file_id/move_or_copy', to: 'folders#move_or_copy_file', as: 'move_or_copy_file'
  get 'folders/:id/bookmark', to: 'folders#bookmark', as: 'bookmark_folder'
  get 'folders/:id/file/:file_id/bookmark', to: 'folders#bookmark_file', as: 'bookmark_file'
  delete 'folders/:id/elements', to: 'folders#delete_elements', as: 'folder_delete_elements'
  post 'folders/:id/files', to: 'folders#create_blank_file'
  patch 'folders/:id/move_or_copy', to: 'folders#move_or_copy_folder', as: 'move_or_copy_folder'
  get 'folders/:id/details', to: 'folders#details', as: 'details_folder'
  get 'folders/:id/files/:file_id/details', to: 'folders#file_details', as: 'details_file'
  get 'folders_search', to: 'folders#search'
  get 'folders_tree', to: 'folders#tree', as: :tree_folder
  get 'folders/:id/zip', to: 'folders#zip', as: :folder_zip

  get 'wopi/files/:id/contents', to: 'wopi#filecontent', as: 'wopi_filecontent'
  post 'wopi/files/:id/contents', to: 'wopi#update_filecontent'
  get 'wopi/files/:id', to: 'wopi#file', as: 'wopi_file'

  get 'end_visio', to: 'external_pages#end_visio', as: 'end_visio'
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  include ParticipantFeature

  belongs_to :participant, touch: true
  has_one :next_meeting, class_name: 'Meeting'

  before_destroy :untie_next_meeting

  def create_weekly(recurring_end_date, recurrence = 1)
    return if next_meeting

    meeting = self
    start = meeting.start_time + recurrence.week
    stop = meeting.end_time + recurrence.week
    while start < recurring_end_date
      meeting = meeting.next_meeting = Meeting.create(name:, start_time: start, end_time: stop, user_id:)
      start = meeting.start_time + recurrence.week
      stop = meeting.end_time + recurrence.week
    end
  end

  def destroy_recurring
    next_meeting&.destroy_recurring
    destroy
  end

  private

  def untie_next_meeting
    meeting = Meeting.find_by(meeting_id: id)
    meeting&.update meeting_id: nil
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < BichikController
  include ActionView::RecordIdentifier
  before_action :set_meeting, only: %i[show edit update destroy]

  def index
    @zoom = false
    @started_at = params.fetch(:started_at, Time.now.beginning_of_day).to_datetime.in_time_zone(current_user.time_zone)
    @start_week = @started_at.beginning_of_week
    @end_week = @started_at.end_of_week
    @dates_of_week = (@start_week.to_date..@end_week.to_date).to_a

    # TODO: with_full? owned? invited? shared? see in Participant_Feature
    @meetings = Meeting.with_invited(current_participant).where(started_at: @start_week..@end_week).order(:started_at)

    @teaching_sequences = current_classroom.teaching_sequences.where(started_at: @start_week..@end_week).order(:started_at)
    @visios = Visio.with_invited(current_participant)
                   .where(started_at: @start_week..@end_week).order(:started_at)
  end

  def show
    return if @meeting.invitations.map { |invitation| invitation.participant_invited?(current_participant) }.any?

    redirect_to meetings_path,
                alert: t('application.law')
  end

  def new
    @meeting = Meeting.new
    at = params[:started_at] ? DateTime.parse(params[:started_at]) : Time.now.in_time_zone(current_user.time_zone)
    @meeting.started_at = at
    @meeting.ended_at = at + 1.hour
  end

  def edit
    redirect_to meetings_path, alert: t('application.law') unless @meeting.participant == current_participant
  end

  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.participant = current_participant
    @meeting.started_at = meeting_params[:started_at].in_time_zone(current_timezone)
    @meeting.ended_at = meeting_params[:ended_at].in_time_zone(current_timezone)

    if @meeting.save
      if params[:invitation]
        redirect_to invitations_path(Meeting.to_s.downcase, @meeting.id, return_path: edit_meeting_path(@meeting))
      else
        redirect_to meetings_path(started_at: @meeting.started_at, anchor: '6'),
                    notice: 'Meeting was successfully created.'
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @meeting.participant == current_participant
      meetingp = meeting_params
      meetingp[:started_at] = meetingp[:started_at].in_time_zone(current_timezone)
      meetingp[:ended_at] = meetingp[:ended_at].in_time_zone(current_timezone)

      if @meeting.update(meetingp)
        if params[:invitation]
          redirect_to invitations_path(Meeting.to_s.downcase, @meeting.id, return_path: edit_meeting_path(@meeting))
        else
          redirect_to meetings_path(started_at: @meeting.started_at, anchor: '6'),
                      notice: 'Meeting was successfully updated.'
        end
      else
        render :edit, status: :unprocessable_entity
      end
    else
      redirect_to meetings_path, alert: t('application.law')
    end
  end

  def destroy
    started_at = @meeting.started_at
    if params[:recursive]
      @meeting.destroy_recurring
    else
      @meeting.destroy
    end
    redirect_to meetings_path(started_at:), notice: 'Meeting was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def meeting_params
    params.require(:meeting).permit(:name, :started_at, :ended_at, :description)
  end
end

app/views/meetings/_form.html.erb
<%# locals: (meeting: nil, readonly: false) %>
<%= form_with(model: meeting, class: "contents") do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>
      <ul>
        <% meeting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='my-4 mx-2 flex flex-col gap-4'>
    <%= build_text_field(form, 'name', 'calendar', autofocus: true, required: true, placeholder: 'Titre du rendez-vous') unless readonly %>
    <%= build_datetime_field_with_label('meeting', 'started_at', meeting.started_at.in_time_zone(current_timezone), 
                                        icon: 'clock', label: 'Date et heure de début', required: true, readonly:) %>
    <%= build_datetime_field_with_label('meeting', 'ended_at', meeting.ended_at.in_time_zone(current_timezone), 
                                        icon: 'clock', label: 'Date et heure de fin', required: true, readonly:) %>
    <%= build_text_area(form, 'description', 'align-left', placeholder: 'Description', rows: 4, readonly:) %>
    <% if meeting.invitations.size.positive? %>
      <div class='flex flex-col'>
        <div><span class='bg-bichik-100 rounded-t-lg p-1 text-sm text-gray-100'>Invité·e·s</span></div>
        <div class='flex flex-row'>
          <%= icon('fa-solid', 'share-alt', class: 'h-auto rounded-bl-lg bg-zourit-1 text-gray-100 text-lg p-2 w-8 text-center') %>
          <span class='bg-gray-100 border border-zourit-1 text-gray-800 text-sm rounded-r-lg w-full pl-5
              p-2 focus:border-zourit-1 focus:ring-1 focus:ring-zourit-1'>
            <div class="flex flex-wrap gap-1">
              <% meeting.invitations.each do |invitation| %>
                <div class='mx-1 text-xs p-1 bg-gray-600 text-white rounded-lg whitespace-nowrap'>
                  <% fa_icon = case invitation.recipient_human_type
                             when 'Participant'
                                invitation.recipient.participant_icon
                             when 'Group'
                                'users'
                             else
                                'globe'
                             end %>
                  <%= icon('fa-solid', fa_icon) %>
                  <%= invitation.recipient_human_name %>
                </div>
              <% end %>
            </div>
          </span>
        </div>
      </div>
    <% end %>
  </div>
  <% unless readonly %>
    <div class="inline">
      <%= form.submit ts('actions.save'), class: "rounded-lg py-3 px-5 bg-bichik-100 hover:bg-bichik-110 text-white inline-block font-medium cursor-pointer mb-2" %>
      <%= form.submit ts(:share), class: "rounded-lg py-3 px-5 bg-bichik-100 hover:bg-bichik-110 text-white inline-block font-medium cursor-pointer mb-2 ml-2",
                    name: 'invitation' %>
    </div>
  <% end %>
<% end %>

app/views/meetings/_visios.html.erb
<% @visios.each do |meeting| %>
  <% beginning = ((meeting.started_at.in_time_zone(current_timezone).hour.to_f + meeting.started_at.min.to_f/60)*pas+2).round(0) %>
  <% duration = ((meeting.duration || 60)*pas/60).round(0) %>
  <% column = @dates_of_week.index(meeting.started_at.to_date) + 1 %>
  <li class="relative mt-px <%= @started_at == meeting.started_at.to_date ? 'flex' : 'hidden' %> sm:flex sm:col-start-<%= column %>" style="grid-row: <%= beginning %> / span <%= duration %>">
    <%= link_to visio_path(meeting), class: "group absolute inset-1 flex flex-col overflow-y-auto rounded-lg bg-red-600 px-2 pt-1 text-xs leading-5 hover:bg-red-700 hover:z-20 shadow border border-gray-800 dark:border-gray-200",
                data: { turbo: false },
                onclick: "loading('Chargement de la visioconférence...')" do %>
      <p class="order-1 font-semibold text-gray-100">
        <%= icon('fa-solid', 'video', class: 'pr-2 text-gray-200') %>
        <%= meeting.name %>
        <% if meeting.invited %>
          <%= icon('fa-solid', 'share-nodes', class: 'pr-2 text-gray-200') %>
        <% end %>
      </p>
      <p class="text-gray-200"><time><%= meeting.started_at.in_time_zone(current_timezone).strftime('%H:%M') %></time></p>
    <% end %>
  </li>
<% end %>

app/views/meetings/index.html.erb
<%= render partial:'application/page_title', 
locals: {
  title: 'Calendrier', 
  icon: 'calendar'
} %>
<%= turbo_stream_from current_user %>

<div class="flex h-full flex-col">
  <header class="flex flex-none items-center justify-between border-b border-gray-200 dark:border-gray-800 bg-gray-700 dark:bg-gray-800 px-6 py-4">
    <h1 class="text-base font-semibold leading-6 text-gray-200">
      <time datetime="<%= @start_week.strftime('%Y-%m') %>"><%= l(@start_week, format: '%B %Y') %></time>
    </h1>
    <div class="flex items-center">
      <div class="relative flex items-center rounded-md bg-white shadow-sm md:items-stretch">
        <%= link_to meetings_path(started_at: @start_week.last_week), class: "flex h-9 w-12 items-center justify-center rounded-l-md border-y border-l border-gray-300 pr-1 text-gray-400 hover:text-gray-500 focus:relative md:w-9 md:pr-0 md:hover:bg-gray-50", data: { turbo_action: 'replace' } do %>
          <span class="sr-only">Previous week</span>
          <%= icon('fa-solid', 'chevron-left', class: 'text-xs') %>
        <% end %>
        <%= link_to "Aujourd'hui", meetings_path(started_at: Date.today), class: "hidden border-y border-gray-300 px-3.5 text-sm font-semibold text-gray-900 hover:bg-gray-50 focus:relative md:flex items-center", data: { turbo_action: 'replace' } %>
        <%= link_to meetings_path(started_at: @start_week.next_week), class: "flex h-9 w-12 items-center justify-center rounded-r-md border-y border-r border-gray-300 pl-1 text-gray-400 hover:text-gray-500 focus:relative md:w-9 md:pl-0 md:hover:bg-gray-50", data: { turbo_action: 'replace' } do %>
          <span class="sr-only">Next week</span>
          <%= icon('fa-solid', 'chevron-right', class: 'text-xs') %>
        <% end %>
      </div>
      <div class="hidden md:ml-2 md:flex md:items-center">
        <div class="relative hidden">
          <button type="button" class="flex items-center gap-x-1.5 rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" id="menu-button" aria-expanded="false" aria-haspopup="true">
            Week view
            <svg class="-mr-1 h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z" clip-rule="evenodd" />
            </svg>
          </button>

          <!--
            Dropdown menu, show/hide based on menu state.

            Entering: "transition ease-out duration-100"
              From: "transform opacity-0 scale-95"
              To: "transform opacity-100 scale-100"
            Leaving: "transition ease-in duration-75"
              From: "transform opacity-100 scale-100"
              To: "transform opacity-0 scale-95"
          -->
          <div class="hidden absolute right-0 z-10 mt-3 w-36 origin-top-right overflow-hidden rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
            <div class="py-1" role="none">
              <!-- Active: "bg-gray-100 text-gray-900", Not Active: "text-gray-700" -->
              <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="menu-item-0">Day view</a>
              <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="menu-item-1">Week view</a>
              <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="menu-item-2">Month view</a>
              <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="menu-item-3">Year view</a>
            </div>
          </div>
        </div>
        <div class="ml-4 h-6 w-px bg-gray-300"></div>
        <%= link_to "Nouveau rendez-vous", new_meeting_path, class: "ml-6 rounded-md bg-zourit-1 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-zourit-2 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500" %>
      </div>
      <div class="relative ml-6 md:hidden">
        <%= link_to new_meeting_path(started_at: @started_at), class: '-mx-2 flex items-center rounded-full bg-bichik-100 hover:bg-bichik-110 p-2 text-gray-100' do %>
          <%= icon('fa-solid', 'plus') %>
        <% end %>

        <!--
          Dropdown menu, show/hide based on menu state.

          Entering: "transition ease-out duration-100"
            From: "transform opacity-0 scale-95"
            To: "transform opacity-100 scale-100"
          Leaving: "transition ease-in duration-75"
            From: "transform opacity-100 scale-100"
            To: "transform opacity-0 scale-95"
        -->
        <div class="hidden absolute right-0 z-10 mt-3 w-36 origin-top-right divide-y divide-gray-100 overflow-hidden rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-0-button" tabindex="-1">
          <div class="py-1" role="none">
            <!-- Active: "bg-gray-100 text-gray-900", Not Active: "text-gray-700" -->
            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="menu-0-item-0">Create event</a>
          </div>
          <div class="py-1" role="none">
            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="menu-0-item-1">Go to today</a>
          </div>
          <div class="py-1" role="none">
            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="menu-0-item-2">Day view</a>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="menu-0-item-3">Week view</a>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="menu-0-item-4">Month view</a>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="menu-0-item-5">Year view</a>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="isolate flex h-[calc(100vh-200px)] sm:h-[calc(100vh-310px)] flex-col overflow-auto bg-white sm:rounded-b-lg">
    <div style="width: 165%" class="flex max-w-full flex-none flex-col sm:max-w-none md:max-w-full">
      <div class="sticky top-0 z-30 flex-none bg-white dark:bg-gray-900 shadow ring-1 ring-black ring-opacity-5 sm:pr-8">
        <!-- xs Day of the week -->
        <div class="grid grid-cols-7 text-sm leading-6 text-gray-500 sm:hidden">
          <% @dates_of_week.each do |date| %>
            <%= link_to meetings_path(started_at: date), class: "flex flex-col items-center pb-3 pt-2", data: { turbo_action: 'replace' } do %>
              <%= l(date, format: '%a')[0] %>
              <% classe = @started_at.to_date == date ? 'text-white ml-1.5 rounded-full bg-bichik-200' : 'text-gray-900 dark:text-gray-200' %>
              <span class="mt-1 flex h-8 w-8 items-center justify-center font-semibold <%= classe %>"><%= date.day %></span>
            <% end %>
          <% end %>
        </div>
        <!-- >=sm Day of the week -->
        <div class="-mr-px hidden grid-cols-7 divide-x divide-gray-100 border-r border-gray-100 dark:divide-gray-800 dark:border-gray-800 text-sm leading-6 dark:bg-gray-900 text-gray-500 dark:text-gray-200 sm:grid">
          <div class="col-end-1 w-14"></div>
          <% @dates_of_week.each do |date| %>
            <div class="flex items-center justify-center py-3">
              <% classe = Date.today == date ? 'text-white ml-1.5 flex h-8 w-8 rounded-full bg-bichik-200 dark:bg-bichik-100' : 'text-gray-900 dark:text-gray-100' %>
              <span class="<%= 'flex items-baseline' if Date.today == date.to_date %>"><%= l(date, format: '%a') %> <span class="items-center justify-center font-semibold <%= classe %>"><%= date.day %></span></span>
            </div>
          <% end %>
        </div>
      </div>
      <div class="flex flex-auto">
        <div class="sticky left-0 z-10 w-14 flex-none bg-white dark:bg-gray-900 ring-1 ring-gray-100 dark:ring-gray-800"></div>
        <div class="grid flex-auto grid-cols-1 grid-rows-1 dark:bg-gray-800">
          <!-- Horizontal lines -->
          <div class="col-start-1 col-end-2 row-start-1 grid divide-y divide-gray-100 dark:divide-gray-700" style="grid-template-rows: repeat(<%= @zoom ? 48 : 24 %>, minmax(3.5rem, 1fr))">
            <div class="row-end-1 h-7"></div>
            <% (0..23).to_a.each do |h| %>
              <div>
                <div id="<%=h%>" class="sticky left-0 z-20 -ml-14 -mt-2.5 w-14 pr-2 text-right text-xs leading-5 text-gray-400"><%= h %> h</div>
              </div>
              <% if @zoom %>
                <div></div>
              <% end %>
            <% end %>
          </div>

          <!-- Vertical lines -->
          <div class="col-start-1 col-end-2 row-start-1 hidden grid-cols-7 grid-rows-1 divide-x divide-gray-100 dark:divide-gray-700 sm:grid sm:grid-cols-7">
            <% (1..8).to_a.each do |col| %>
              <div class="col-start-<%=col%> row-span-full <%= 'w-8' if col==8 %>"></div>
            <% end %>
          </div>

          <ol class="col-start-1 col-end-2 row-start-1 grid grid-cols-1 sm:grid-cols-7 sm:pr-8" style="grid-template-rows: 1.75rem repeat(288, minmax(0, 1fr)) auto">
            <% pas = 12 %>
            <!-- Heures cliquables -->
            <% (0..23).to_a.each do |h| %>
              <% (1..7).to_a.each do |col| %>
                <% date = @dates_of_week[col-1] %>
                <% Time.zone = current_user.time_zone %>
                <% datetime = Time.zone.strptime("#{date.year}-#{date.month}-#{date.day} #{h}:00:00", '%Y-%m-%d %H:%M:%S') %>
                <li class="relative mt-px hidden sm:flex sm:col-start-<%= col %>" style="grid-row: <%= h*pas+2 %> / span <%= pas %>">
                  <%= link_to new_meeting_path(started_at: datetime), class: "absolute inset-1 flex flex-col overflow-y-auto leading-5 hover:bg-gray-200 dark:hover:bg-gray-600 justify-center items-center" do %>
                    <%= icon('fa-solid', 'plus', class: 'fa-2x text-white dark:text-gray-800') %>
                  <% end %>
                </li>
              <% end %>
            <% end %>

            <!-- Events -->
            <%= render 'teaching_sequences', pas: %>
            <%= render 'meetings', pas: %>
            <%= render 'visios', pas: %>
          </ol>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/meetings/new.html.erb
<%= render partial:'application/page_title', 
locals: {
  title: 'Nouveau rendez-vous', 
  icon: 'calendar'
} %>
<div class="mx-auto md:w-2/3 w-full">

  <%= render "form", meeting: @meeting %>

  <%= link_to ts('actions.cancel'), 
              meetings_path(start_at: @meeting.started_at, anchor: '6'), 
              class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 text-gray-800 inline-block font-medium mb-4" %>
</div>