config/routes.rb
Rails.application.routes.draw do
  root 'participants#index'

  resources :shuttle_forms, only: %i[index edit update]
  post 'shuttle_forms/menu/:id', to: 'shuttle_forms#turbo_menu', as: :shuttle_form_menu

  mount ActionCable.server => '/cable'
  resources :folders
  resources :meetings
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords' }
  resources :links, except: %i[show]

  resources :pads
  post 'pads/:id/toggle_archive', to: 'pads#toggle_archive', as: 'pad_toggle_archive'
  post 'pads/:id/toggle_bookmark', to: 'pads#toggle_bookmark', as: 'pad_toggle_bookmark'

  resources :visios
  post 'visios/:id/toggle_archive', to: 'visios#toggle_archive', as: 'visio_toggle_archive'
  post 'visios/:id/toggle_bookmark', to: 'visios#toggle_bookmark', as: 'visio_toggle_bookmark'
  get 'visios/:id/visio_url', to: 'visios#url', as: 'visio_url'
  get '/visios/:id/button_to_bbb', to: 'visios#button_to_bbb', as: 'button_to_bbb'
  get '/visios/:id/recordings', to: 'visio_recordings#index', as: 'visio_recordings'
  delete 'visios/:id/recordings/:record_id' => 'visio_recordings#destroy', as: 'visio_recordings_destroy'
  get '/visios/:id/recordings_list', to: 'visio_recordings#visio_recordings', as: 'visio_recordings_list'
  get 'visios/:id/recordings/after_destroy', to: 'visio_recordings#after_destroy', as: 'visio_recordings_after_destroy'
  get 'visios/:id/recordings/:record_id/download', to: 'visio_recordings#download', as: 'visio_recording_download'

  resources :memos
  post 'memos/:id/toggle_archive', to: 'memos#toggle_archive', as: 'memo_toggle_archive'
  post 'memos/:id/toggle_bookmark', to: 'memos#toggle_bookmark', as: 'memo_toggle_bookmark'

  resources :users, only: %i[edit update]

  resources :config_modules do
    resources :instances
  end

  resources :services, only: %i[index show]

  # Choix de la promo
  get 'participants', to: 'participants#index', as: 'participants'
  post 'participants/:id', to: 'participants#choose', as: 'participant'

  resources :classrooms
  get 'classrooms/:id/groups', to: 'groups#index', as: 'groups'
  post 'classrooms/:id/groups', to: 'groups#create'
  get 'classrooms/:id/groups/:group_id', to: 'groups#show', as: 'group'
  delete 'classrooms/:id/groups/:group_id', to: 'groups#destroy'
  patch 'classrooms/:id/groups/:group_id', to: 'groups#update', as: 'group_update'
  post 'classrooms/:id/participant/:participant_id/enable_module/:module_id', to: 'classrooms#enable_module_for_participant',
                                                                              as: 'enable_module_for_participant'
  post 'classrooms/:id/participant/:participant_id/disable_module/:module_id', to: 'classrooms#disable_module_for_participant',
                                                                               as: 'disable_module_for_participant'

  post 'login' => 'users#login'
  get 'logout' => 'users#logout', as: :logout

  get 'about' => 'about#index', as: 'about'

  get 'config_modules/:domain_id/infos' => 'config_modules#infos'

  get 'invitations/from/:invitable_type/:invitable_id', to: 'invitations#index', as: :invitations
  get 'invitations/from/:invitable_type/:invitable_id/groups', to: 'invitations#invite_per_groups',
                                                               as: :invite_per_groups
  post 'invitations/from/:invitable_type/:invitable_id/group/:id', to: 'invitations#invite_group_add',
                                                                   as: :invite_group_add
  delete 'invitations/from/:invitable_type/:invitable_id/group/:id', to: 'invitations#invite_group_del',
                                                                     as: :invite_group_del
  post 'invitations/from/:invitable_type/:invitable_id/participant/:id', to: 'invitations#invite_participant_add',
                                                                         as: :invite_participant_add
  delete 'invitations/from/:invitable_type/:invitable_id/participant/:id', to: 'invitations#invite_participant_del',
                                                                           as: :invite_participant_del
  get 'invitations/from/:invitable_type/:invitable_id/participants', to: 'invitations#invite_per_participants',
                                                                     as: :invite_per_participants
  post 'invitations/from/:invitable_type/:invitable_id/emails', to: 'invitations#invite_per_emails',
                                                                as: :invite_per_emails
  patch 'invitations/from/:invitable_type/:invitable_id/emails', to: 'invitations#invite_per_emails_submit',
                                                                 as: :invite_per_emails_submit
  post 'invitations/from/:invitable_type/:invitable_id/groups/:id', to: 'invitations#invite_add_group',
                                                                    as: :invite_one_group
  patch 'invitations/:id', to: 'invitations#resend', as: :resend_invitation
  delete 'invitations/:id', to: 'invitations#destroy', as: :destroy_invitation

  get 'folders/:id/files/:file_id', to: 'folders#file', as: 'file'
  patch 'folders/:id/files/:file_id', to: 'folders#rename_file', as: 'rename_file'
  delete 'folders/:id/files/:file_id', to: 'folders#delete_file', as: 'delete_file'
  patch 'folders/:id/files/:file_id/move_or_copy', to: 'folders#move_or_copy_file', as: 'move_or_copy_file'
  get 'folders/:id/bookmark', to: 'folders#bookmark', as: 'bookmark_folder'
  get 'folders/:id/file/:file_id/bookmark', to: 'folders#bookmark_file', as: 'bookmark_file'
  delete 'folders/:id/elements', to: 'folders#delete_elements', as: 'folder_delete_elements'
  post 'folders/:id/files', to: 'folders#create_blank_file'
  patch 'folders/:id/move_or_copy', to: 'folders#move_or_copy_folder', as: 'move_or_copy_folder'
  get 'folders/:id/details', to: 'folders#details', as: 'details_folder'
  get 'folders/:id/files/:file_id/details', to: 'folders#file_details', as: 'details_file'
  get 'folders_search', to: 'folders#search'
  get 'folders_tree', to: 'folders#tree', as: :tree_folder
  get 'folders/:id/zip', to: 'folders#zip', as: :folder_zip

  get 'wopi/files/:id/contents', to: 'wopi#filecontent', as: 'wopi_filecontent'
  post 'wopi/files/:id/contents', to: 'wopi#update_filecontent'
  get 'wopi/files/:id', to: 'wopi#file', as: 'wopi_file'

  get 'end_visio', to: 'external_pages#end_visio', as: 'end_visio'
end

app/models/memo.rb
class Memo < ApplicationRecord
  include ParticipantFeature

  before_create :add_uuid
  validates_presence_of :name

  @default_sort = 'name'

  def owner = user

  def external_url(classroom)
    mod = ConfigModule.where(name: 'Framemo').first
    url_server = mod.instance_for_classroom(classroom).url
    url_embedded = url_server
    url_embedded += '/' unless url_server[-1] == '/'
    url_embedded += uuid
    url_embedded
  end

  private

  def add_uuid = self.uuid = UUIDTools::UUID.random_create.to_s
end

app/controllers/memos_controller.rb
class MemosController < BichikController
  include BookmarkableController

  before_action :framemo_authorized!
  before_action :set_pagy_memos, only: :index
  before_action :set_memo, except: %i[index new create]
  before_action :create_authorized!, only: %i[new create]
  before_action :modify_authorized!, only: %i[edit update destroy]

  def index; end

  def show
    @type_page = 'iframe'
    config_module = ConfigModule.find_by(name: 'Framemo')
    domain_info = DomainInfo.find_by(classroom: current_classroom, config_module:)
    url_server = domain_info.instance.url
    if url_server
      @url_embedded = url_server
      @url_embedded += '/' unless @url_embedded[-1] == '/'
      @url_embedded += @memo.uuid
    else
      redirect_to services_path, notice: (I18n.t 'modules.framemo.noactif').to_s
    end
  end

  def new
    @memo = Memo.new
  end

  def edit; end

  def create
    @memo = Memo.new(memo_params)
    @memo.participant = current_participant

    if @memo.save
      redirect_to @memo, notice: I18n.t('modules.framemo.noticecreate', memo_name: @memo.name)
    else
      render_turbo_error(@memo, turbo_frame: 'memo_form', partial: 'form')
    end
  end

  def update
    if @memo.update(memo_params)
      redirect_to memos_path, notice: I18n.t('modules.framemo.noticeupdate', memo_name: @memo.name)
    else
      render_turbo_error(@memo, turbo_frame: 'memo_form', partial: 'form')
    end
  end

  def destroy
    @memo.destroy
    redirect_to memos_path, notice: I18n.t('modules.framemo.noticedestroy')
  end

  def toggle_archive
    @memo.toggle_archive(current_participant)
    redirect_to memos_path(q: q_params)
  end

  def toggle_bookmark
    @memo.toggle_bookmark(current_participant)
    redirect_to memos_path(q: q_params)
  end

  private

  def framemo_authorized! = config_module_authorized!('Framemo')
  def create_authorized! = not_tutoring(memos_path)
  def modify_authorized! = only_owner!(@memo.participant, memos_path)

  def memo_params = params.require(:memo).permit(:name, :comment)
  def q_params = params.fetch(:q, {}).permit!

  def filtering
    filter = q_params.slice(:archived)
    filter[:archived] ||= false
    filter
  end

  def set_pagy_memos
    memos = Memo.with_full(current_participant, filtering:)
    @q = memos.ransack(default_bookmarkable_sort(q_params, Memo))
    @pagy, @memos = pagy(@q.result)
  end

  def set_memo
    @memo = Memo.find_full(current_participant, params[:id])
  end
end

app/views/memos/_form.html.erb
<%= turbo_frame_tag :memo_form, target: '_top' do %>
  <%= form_for(@memo) do |f| %>
    <%= render 'forms/makeup' do %>
      <%= render 'forms/error_messages', model: @memo %>

      <!-- FORM FIELDS -->
      <%= build_text_field(f, :name, autofocus: true) %>
      <%= build_text_area(f, :comment) %>

      <%= render 'forms/actions', cancel_path: memos_path %>
    <% end %>
  <% end %>
<%end%>

app/views/memos/_memo.html.erb
<tr class="text-sm even:bg-gray-100 dark:even:bg-gray-900 dark:text-gray-200">
  <td class="py-3 px-2">
    <%= button_to memo_toggle_bookmark_path(memo.id, preserve_q) do %>
      <i class="fa<%= 'r' unless memo.bookmarked %> fa-bookmark" title='<%= ts(memo.bookmarked ? 'actions.delete_bookmark' : 'actions.add_bookmark') %>'></i>
    <% end %>
  </td>
  <td class="px-2 w-full md:w-1/4">
    <%= link_to highlight(memo.name, params.dig(:q,'name_or_comment_or_participant_user_last_name_or_participant_user_first_name_cont')), memo, title: memo.comment, class: "font-bold text-zourit-1 hover:text-gray-200", data: { toggle: 'tooltip', placement: 'bottom', turbo: false } %>
  </td>
  <td class="px-2 hidden lg:table-cell w-full">
    <%= highlight(memo.comment&.truncate(80, separator: /\s/), params.dig(:q,  'name_or_comment_or_participant_user_last_name_or_participant_user_first_name_cont')) %>
  </td>
  <td class="lg:whitespace-nowrap hidden sm:table-cell">
    <% if memo.shared %>
      <%= icon 'fa-solid', 'square-share-nodes', title: ts('shared.shared') %>
    <% elsif memo.invited %>
      <%= icon 'fa-solid', 'share-alt', title: ts('shared.invited_by', user_name: memo.participant.name) %>
    <% end %>
  </td>
  <td class="px-2 lg:whitespace-nowrap hidden sm:table-cell">
    <%= highlight(memo.participant.name, params.dig(:q,  'name_or_comment_or_participant_user_last_name_or_participant_user_first_name_cont')) %>
  </td>
  <td class="px-2 hidden md:table-cell lg:whitespace-nowrap">
    <%= memo.created_at.in_time_zone(current_timezone).strftime("%d/%m/%Y %H:%M") %>
  </td>
  <td class="">
    <div class="flex mr-2 gap-2" data-controller="clipboard">
      <input hidden value="<%= memo.external_url(current_classroom)%>" data-clipboard-target="source">
      <span class='flex flex-nowrap' %>
        <%= buttons_box [
          { 
            href: memo_path(memo),
            icon: :eye,
            title: t(:access), 
            data: { toggle: 'tooltip', placement: 'bottom', turbo: false },
            onclick: "loading('Chargement de la memoconférence...')"
          },
          {
            icon: :clipboard,
            title: t('actions.copy_external_link_to_clipboard'),
            data: { action: 'clipboard#copy' }
          },
          {
            href: memo_toggle_archive_path(memo.id, preserve_q),
            icon: memo.archived ? 'box-open' : 'box-archive',
            title: memo.archived ? t('actions.unarchive') : t('actions.archive'),
            data: { turbo_method: :post }
          }
        ] %>
      </span>
      <span class='flex flex-nowrap'>
        <% if memo.owned %>
          <% buttons = [] %>
          <% if !memo.archived %>
            <% 
            buttons << {
                href: edit_memo_path(memo),
                icon: :pencil,
                title: t(:edit),
                data: { turbo: false }
            } 
            buttons << { 
                href: invitations_path(Memo.to_s.downcase, memo.id),
                icon: :users,
                title: t(:share),
                data: { turbo: false }
            } %>
          <% end %>
          <% buttons << {
            href: memo_path(memo),
            icon: :trash,
            title: t(:delete),
            data: { turbo_method: :delete, turbo_confirm: t(:delete_confirm) }
          } %>
        <% end %>
        <%= buttons_box buttons %>
      </span>
    </div>
  </td>
</tr>

app/views/memos/_memos.html.erb
<%= turbo_frame_tag :memos do %>
  <div class='overflow-x-auto'>
    <table class="min-w-full divide-gray-100 dark:divide-gray-700 divide-y">
      <thead>
        <tr class="whitespace-nowrap text-md text-left font-semibold text-gray-800 dark:text-gray-200 bg-gray-100 dark:bg-gray-700">
          <th scope="col"></th>
          <th scope="col" class="p-2">
            <%= pagy_sort_link(@q, :name, ts('activerecord.attributes.memo.name')) %>
          </th>
          <th scope="col" class="p-2 hidden lg:table-cell">
            <%= pagy_sort_link(@q, :comment, ts('activerecord.attributes.memo.comment')) %>
          </th>
          <th scope="col" class="p-2 hidden sm:table-cell">
            <%= pagy_sort_link(@q, :shared, [:shared, :invited]) do %>
              <%= icon 'fa-solid', 'share-alt', title: ts('shared.shared') %>
            <% end %>
          </th>
          <th scope="col" class="p-2 hidden sm:table-cell">
            <%= pagy_sort_link(@q, :participant_user_last_name, [:participant_user_last_name, :participant_user_first_name], 
                  ts('shared.creator')) %>
          </th>
          <th class='p-2 hidden md:table-cell'>
            <%= pagy_sort_link(@q, :created_at, ts('shared.createdate')) %>
          </th>
          <th class='flex justify-end align-bottom m-2'>
            <span class='pt-0.5 pr-2'>
              <%= icon('fa-solid', 'box-archive', title: ts('actions.archive_toggle_on')) %>
            </span>
            <%= pagy_toggle_link(@q,:archived, title: ts('actions.archive_toggle_on')) %>
          </th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
        <%= render @memos %>
      </tbody>
    </table>
  </div>

  <%= render 'application/pagy_bar' %>
<%end%>

app/views/memos/edit.html.erb
<%= render 'application/page_title',
  title: t('modules.framemo.modifmemo'), 
  icon: icon('fa-solid','Framemo'), 
  back: { url: memos_path, title: t('modules.framemo.memolist') } 
%>

<%= render 'form' %>

app/views/memos/index.html.erb
<%= render 'application/page_title', 
           title: t('modules.framemo.memolist'),  
           icon:  module_icon('Framemo') %>
<div class='grid grid-cols-1 lg:grid-cols-3 mt-4 gap-2'>
  <div></div>
  <%= render 'application/search',
           form_path: memos_path,
           attribute: 'name_or_comment_or_participant_user_last_name_or_participant_user_first_name_cont' %>
  <div class='flex justify-center lg:justify-end items-center lg:mr-4'>
    <%= link_to new_memo_path, 
      class: 'btn-primary' do %>
      <%= fa_icon 'plus' %>
      <%= ts('modules.framemo.newmemo') unless current_participant.tutoring? %>
    <% end %>
  </div>
</div>
<div class="p-4 inline-block w-full align-middle">
  <%= render "memos" %>
</div>

app/views/memos/new.html.erb
<%= render partial:'application/page_title', locals: {title: t('modules.framemo.addmemo'), icon: module_icon('Framemo'), back: { url: memos_path, title: t('modules.framemo.memolist') }} %>

<%= render 'form' %>

app/views/memos/show.html.erb
<% content_for :title, @memo.name %>

<div class="zourit-iframe">
  <iframe src="<%= @url_embedded %>" width=100% frameborder="0" scrolling="yes"></iframe>
</div>